name: Greetings

# on: [pull_request, issues]
on: issues

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hello @${{ github.actor }},
          Thanks for finding the time to report the issue!
          We really appreciate the community's efforts to improve Apache Kyuubi (Incubating).
        pr-message: |
          Hello @${{ github.actor }},
          Thanks for finding the time to submit the Pull request, the Kyuubi community thanks you！
          We really appreciate the community's efforts to improve Apache Kyuubi (Incubating).
          If you are new to Apache Kyuubi for code changes, please take some time to read our [contributing guide](https://kyuubi.apache.org/contributing.html).
